env:
  browser: true
  node: true
  mocha: true
  es6: true
  jquery: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
parser: 'babel-eslint'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: 0
  no-trailing-spaces:
    - error
  comma-dangle:
    - error
    - never
